/**
 * Need to be on client because use of MUI theme here.
 */
"use client";
import NavBar from "../components/Navbar/NavBar";
import { Container } from "@mui/material";
import { ThemeProvider, useMediaQuery } from "@mui/material";
import { Inter } from "next/font/google";
import { lightTheme, darkTheme } from "./theme";

import CssBaseline from "@mui/material/CssBaseline";
import { Provider } from "react-redux";
import { store } from "./store";
import InfoModal from "../components/InfoModal/infoModal";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    const prefersDarkMode = useMediaQuery("(prefers-color-scheme: dark)");
    const theme = prefersDarkMode ? darkTheme : lightTheme;

    return (
        <Provider store={store}>
            <ThemeProvider theme={theme}>
                <CssBaseline />
                <html lang="en">
                    <body className={inter.className}>
                        <InfoModal />
                        <NavBar />
                        <Container style={{ marginTop: "56px" }}>
                            {children}
                        </Container>
                    </body>
                </html>
            </ThemeProvider>
        </Provider>
    );
}
